package com.sample.wordcount.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Custom ErrorDto Required to pass on custom Error Code and messages in
 * Response Body
 * 
 * @see com.sample.wordcount.exception.GlobalExceptionHandler#handleInvalidInputException(com.sample.wordcount.exception.types.InvalidInputException)
 * 
 * @author Ankit Kumar Singh
 */
@AllArgsConstructor
@Data
public class ErrorResponseDto {

	@Schema(name = "appErrorCode", description = "Custom Error Code generated by application", example = "ERR00X")
	String appErrorCode;

	@Schema(name = "appErrorMessage", description = "Custom Error message generated by application", example = "Sample Error Message")
	String appErrorMessage;

}
